### ISSUE TITLE
Problematic alphabet letters

### ISSUE THREAD

**Issue by stanreee** [stanreee/sign-language-learning#102]
Below is a list of all problematic alphabet letters that should be addressed (with more training data):

- D -> inconsistent, sometimes gets confused with K (turns into K when finger points towards webcam)
- E -> inconsistent, low confidence, gets confused with A and S
- F -> inconsistent when pointing towards camera
- G -> usually works pretty well, but orientations might cause it to get confused with Q
- H -> works pretty well
- I -> needs a bit more training, usually consistent but confidence varies
- K -> probably the most troublesome, needs to be focused on
- L -> works pretty well, needs a bit more training on other orientations
- M -> works pretty well only when oriented a certain way, needs more training for other orientations (particularly when tilted left/right and forward)
- N -> needs more training, gets confused with lots of letters (M, D, …)
- O -> needs more training when oriented away from camera or towards camera, gets mixed up with C often
- P -> occasionally gets mixed up with Q, needs a bit more training
- R -> works consistently usually, needs more training with different orientations
- S -> needs more training with orientations tilted towards camera and away
- T -> needs more training with all orientations, oftentimes mixed up with A
- U -> low confidence, gets confused with R and V, needs more training
- V -> low confidence, gets confused with K
- X -> high confidence only when oriented a certain way

**Comment by CassieBaldin** [comment]
Training instructions can be found here!

**Comment by CassieBaldin** [comment]
Lots of training data has been added including in these commits, as well as many others:
3f80c60, bcf2dc2, 5793958, 8723738, ec1a46d
