### ISSUE TITLE
Meeting #7: Andrew, Stanley, Cassidy present (Wed, September 26, 2023 12:30-1:30pm)

### ISSUE THREAD

**Issue by CassieBaldin** [stanreee/sign-language-learning#12]
Agenda: Divide up work for SRS document
- need to add ASLC and Professor Wiesblatt to stakeholders list
- need to talk about when to meet with Professor Wiesblatt

**Comment by stanreee** [comment]
Decided on division of work on SRS sections:

- Section 1: Andrew
- Section 2: Stanley
- Section 3: Cassidy
- Section 4: Jeremy and Edward

Functional requirements categories (something we should look out for during the meeting with ASL club):

- Frontend Requirements
- Backend Requirements
- Computer Vision Model Requirements

Also decided on adding traceability matrix after functional and non-functional requirements are finalized

**Comment by CassieBaldin** [comment]
Actions: Everyone try to work on their section as much as they can, might look over/redivide work on Friday
