### ISSUE TITLE
Meeting with McMaster ASLC: All members present (Tues, October 3, 2023 7:00 - 8:00pm)

### ISSUE THREAD

**Issue by stanreee** [stanreee/sign-language-learning#15]
Meeting with McMaster American Sign Language Club.

Questions to ask:

- Common expressions for beginners
- What kind of progression do they recommend for beginners?
- How did they learn how to use sign language?
- How much variability is in a specific sign language action?
- What concerns might they have with facing a camera that cannot recognize 3D motions? Is that a limiting factor to consider?

**Comment by edwardzhuang2001** [comment]
dominant hand important

**Comment by CassieBaldin** [comment]
Meeting notes:
- Helpful for individuals to practice on their own instead of watching someone else do it
- Resources are deaf creators or teachers of ASL
- There are differences in how some signs can be done (two ways to do "how")
- Handedness can affect how people sign as well (dominant hand is used more often)
- Symmetrical and asymmetrical hand signs, palm in/out
- Body language is also important, not just signs (maybe we can use the default sign and add a note/video to show that expressions matter after teaching?)
- Facial expressions (furrowed brows) are important for questions (who what where when why?)
- Like any language speed varies for fluent and beginners
-  Difference between signing yourself and watching someone else do something (finger signing)
- Able to change speed of video to faster or slower (if we have a practice to say what is being signed, may change difficulty)

**Comment by stanreee** [comment]
**Rough notes**

Beginner progression recommendations:

- some sources provided by sign language instructors
- regional differences (Toronto vs. Hamilton differences, etc.)

Are signs distinct?:
- signs depend on your dominant hand (left-handed vs right-handed)
- some signs use one hand, some signs use two hands
- you may show both hands and only move one hand
- 70% body language, 30% hand signs
furrowed brows changes the meaning sometimes
for intonation, questions require some things beyond hand signs

- context is important
f vs. 9, signed the same but context (like homophones)

variability:


difference between understanding other signs vs. signing yourself
- understanding different sign speeds (increasing sign speed helps with learning understanding)

can't translate 1 to 1 from english to sign language and vice versa

different aspects of sign language (speaking, reading, writing equivalent for other languages)
- you can produce the sign and recognize signs (speaking and listening equivalent)

phrases/words to be as inclusive as possible (so we don't offend):
- not all deaf/hard of hearing people might not use ASL
if you encounter someone who's deaf/hard of hearing you should ask if you should use sign language
- deaf vs Deaf

- university for the deaf: Gallaudet University


is the learning model similar to the one that duolingo uses sufficient for learning sign language? like are there distinct stages that students go through?
- yes but also no, duolingo is good for growing vocabulary size (like learning what a word corresponds to what sign), in terms of being receptive, not really good
- they've only seen applications that show you the sign and tells you what word it is

showing videos where you see a person signing and you have to choose the correct sentence

most signs are from the chest to the head (need to consider the framing of the person)

**Comment by jlangner15** [comment]
- Most ASL learning techniques and apps contain videos and instructors
- ASL is not universal within regions 
- Multiple sign gestures for a single resources
- Must be dominant hand
- Facial gestures also affect tone and emphasis
- Context does matter to words that are the same
- Locations matter as well on the face
- Exert for facial expressions in instructions
- Speed is a factor within hand gestures
- Difference between when someone else is signing vs theirself
- Multiple speeds for videos
- English to ASL is difficult as there are no 'word connectors' and sentence structure is different
- Not all deaf or heart of hearing people will use ASL, always ask for sign language or alternative
- Not much terminology specific to ASL
- Use heart of hearing vs hearing impaired
- Deaf vs deaf have different meanings
- 'handspeak' contains signs and videos or lifeprint or Gallaudet University

Links:
https://import.cdn.thinkific.com/680344/courses/1935589/ASL1and2Introduction_ASLOnlineClassApproachASLLinguistic-220912-131810.pdf
https://www.nad.org/resources/american-sign-language/community-and-culture-frequently-asked-questions/
