### ISSUE TITLE
Meeting #9: All members present (Wed, October 4, 2023 12:30-1:00pm)

### ISSUE THREAD

**Issue by CassieBaldin** [stanreee/sign-language-learning#16]
Agenda: Go over remaining parts of the SRS, split up work accordingly
- Need a traceability matrix
- Finish the NFR fit criterion
- User and documentation section additions
- Reflection section
- Need to add some sort of math/proof/finite state machine to SRS - maybe not
- Need to add likely changes

Actions:
- Cassidy: NFR fit criterion
- Andrew, Stanley: Traceability Matrix
- Jeremy: Reflection
- Edward: User and documentation section additions, likely changes

**Comment by jlangner15** [comment]
I can do the reflection

**Comment by edwardzhuang2001** [comment]
User and documentation section additions
