### ISSUE TITLE
Team17 Review: SRS - ambiguous fit criterion for NFRs

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#24]
For the fit criterion for various NFRs in section 3, for example Security requirements, and cultural requirements, 
*"The developers shall certify the product complies with these requirements."* seems ambiguous and could be replaced by more specific means to verify if the requirement has been met. This could be helpful during testing. (E.g. a percentage threshold of successful attempts, a yes/no question of whether an action is achieved)

(marking TA: @Lyuyang0130 )

**Comment by Tusharagg1** [comment]
@mohaanshpranjal Assign label "Review--Team17"

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I added more information to the fit criterion of some of these NFRs to ensure that each requirement was more verifiable, and included how we plan to ensure each requirement can be tested to the best of our abilities.
