### ISSUE TITLE
Team17 Review: SRS - info on stakeholders

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#25]
There is little info given about the stakeholders and users of this product. Describing attributes, behavior and objectives of the stakeholders would be helpful in the design process in terms of design choices that promote accessibility or are made to enhance user experience.

(@Lyuyang0130 )

**Comment by Tusharagg1** [comment]
@mohaanshpranjal Assign label "Review--Team17"

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I added more information about our stakeholders and what we want them to be able to achieve with our project, as well as some more information on some characteristics of our stakeholders.
