### ISSUE TITLE
Team17 Review: SRS - ambiguous performance requirement

### ISSUE THREAD

**Issue by Ibrahimango02** [stanreee/sign-language-learning#26]
PR1 - The system should respond to user input quickly.

How quick? Might be useful to provide a metric for later testing and verification of the NFR. 

(TA: @Lyuyang0130)

**Comment by Tusharagg1** [comment]
@Ibrahimango02 Assign label "Review--Team17"

**Comment by CassieBaldin** [comment]
In the fit criterion of PR1 it is stated that "95% of tests should respond to user input within 1 second" which is a metric that we will be focusing on later to verify that this NFR has been complete. We did not want to specify those metrics in the description of the requirement as it would be too constraining. 
Thanks for the feedback!
