### ISSUE TITLE
Team17 Review: SRS - Missing formalized portion

### ISSUE THREAD

**Issue by Ibrahimango02** [stanreee/sign-language-learning#27]
The SRS document is missing a formalized section in clear mathematical notation which is a requirement for the SRS submission.

(TA: @Lyuyang0130)

**Comment by Tusharagg1** [comment]
@Ibrahimango02 Assign the label "Review--Team17" from the list of labels (check right hand side)

**Comment by edwardzhuang2001** [comment]
There is no relevant formalized math for our project. This was also not deemed an issue by Dr. Smith or our TA.
