### ISSUE TITLE
Team17 Review: SRS - legal requirement LR1

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#28]
*"The system should adhere to user privacy laws."*
It would be useful to expand on or specify the privacy laws in question.

(TA: @Lyuyang0130 )

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I added more clarity to which specific Canadian law we want to adhere to and how we will be validating this requirement.

**Comment by smiths** [comment]
@CassieBaldin for full transparency and traceability, you can include the commit hash that closes the issue as part of your response.  Don't worry about it for this issue, but in the future, it is good practice to include a link to the commit that addressed the issue.

**Comment by CassieBaldin** [comment]
Thanks @smiths! I have added the correct marker to point to where the changes were made for each closed issue now :)

**Comment by smiths** [comment]
Looks good @CassieBaldin, although in the future you should aim for a more precise traceability, so that the reviewer can find what specific commit closed which specific issue.  Having a finer granularity for your pull requests will accomplish this.  :smile:
