### ISSUE TITLE
Team17 Review: SRS - Security requirement SR2

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#29]
SR2 description states: *"The system should ensure that incorrect input to the system is used."*
I believe this is a typo - the system should ensure that "correct input" is used to train the system.
Additionally, there should be some idea of how an input is verified to be correct.

(TA: @Lyuyang0130 )

**Comment by Tusharagg1** [comment]
@mohaanshpranjal Assign the label "Review--Team17" from the list of labels (check right hand side)

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I fixed the typo and added more clarity to this requirement and its fit criterion to validate this.
