### ISSUE TITLE
Team17 Review: HA - Missing System Boundaries

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#35]
The "Hazard analysis" document is missing System Boundaries. System boundaries define the limits of the system's context and the associated environment in which it operates.

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130 
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I have now included our system boundaries in section 3 of this document. 

You can view the changes here: 46111d6

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/d0c5289e-bcf8-4c57-8f31-abd361f5eb5c)
