### ISSUE TITLE
Team17 Review: HA - Critical Assumptions are unclear/missing

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#36]
- We think the current critical assumptions are too vague assume.
  - What type of users and what is their intended purpose? Are there more than one intended purpose? Do users include all kinds of populations?
- Missing some important critical assumptions such as,
  - The hardware components are reliable and will function without significant failures.
  - The hardware connectivity is universal across all types of devices and operating systems.
  - The application will be available all the time with minimal downtime.
 - etc.

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130 
[Review-Team17]

**Comment by jlangner15** [comment]
Addressed in commit f1003ab on FinalDoc branch
