### ISSUE TITLE
Team17 Review: HA - Additions to FMEA

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#37]
It would be good to consider more possibilities such as:

For 'User authentication error",
- Effects of Failure:
  - The user is locked out
  - User can not access the application
  - User credentials are automatically reset
- Causes of Failure:
  - What kind of user error?
  - App connection to login database is lost
 
For "Database Access",
- Failure Modes:
  - Database is corrupt OR lost
- Effects of Failure:
  - All user data is lost
- Causes of Failure:
  - Database is compromised

Similarly, more to add to other "Design Functions" in the table.

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by jlangner15** [comment]
Addressed in commit f1003ab on FinalDoc branch
