### ISSUE TITLE
Team17 Review: HA - Corrections to "Design Function" in FMEA

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#38]
_FYI, this is a minor issue._

For the first "Design Function" in the FMEA table, it should be "**User authentication**" instead of "User authentication error". This comment is based on the wording of other design functions listed in the table.

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks, this has been fixed now. You can view the changes here: 46111d6

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/a2723e78-ab3b-4b1d-a2e1-f85a7bd1f4ac)
