### ISSUE TITLE
Team17 Review: HA - Missing Rationale and Fit Criterion

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#39]
Please let us know if the document was not intended to include the following.

Based on the format of your team's SRS document, the HA document is missing the 'Rationale' and 'Fit Criterion' for the Safety and Security Requirements.

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I have now added in rationale's and fit criterion for all the safety and security requirements. 

You can view the changes here: 3a43927
