### ISSUE TITLE
Team17 Review: HA - Roadmap - Timeline, Suggestions

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#40]
I would recommend adding a timeline to the Roadmap such that it provides an idea to the team and the stakeholders to know when these requirements will implemented.

Also, I think that some of the Hardware Requirements should be prioritized more than other requirements such as, _'The system shall inform the user that the camera is inoperable.'_

This issue was created by Team 17 as part of the HA Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by jlangner15** [comment]
Addressed in commit f1003ab on FinalDoc branch
