### ISSUE TITLE
Meeting #13: Edward busy, rest present (Fri, Nov 3, 2023 12:30-1:30pm)

### ISSUE THREAD

**Issue by CassieBaldin** [stanreee/sign-language-learning#43]
Agenda: Go over the VnV report, figure out what is still left to be done.

Actions: Need to finish reflection section, add abbreviations section, add traceability matrix., add usability survey questions
- everyone completes their own individual section of the reflection, then add it to the document
- Edward will add his section later on

**Comment by jlangner15** [comment]
Complete 4.3 and self reflection
