### ISSUE TITLE
Team17 Review: VnV - SRS review details

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#48]
It would be helpful to add a checklist or some details about what you want to verify (or how) in the SRS. For example, checking that all fit criterion are feasible or traceability is high enough.

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
The plan for verifying the requirements of the SRS are shown in section 4.2 in the VnV plan (shown below), as well as being verified in the VnV report found here:
https://github.com/stanreee/sign-language-learning/blob/main/docs/VnVReport/VnVReport.pdf

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/ff2e7647-c4bd-4ca5-98e4-b37e316f4405)
