### ISSUE TITLE
Team17 Review: VnV - Performance requirement test #3

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#49]
> NFRT2 - PT3
> Goal: The system should show the user if their input needs to be adjusted.

This would fit more adequately in usability requirements, as it is made to facilitate and enhance user interaction and provides feedback so user can make modifications to the input

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I agree that this requirement does seem like more of a usability requirement than performance so I have changed this in the SRS as well as in the VnV plan to better suit the category.

You can view the changes here: e573adc
