### ISSUE TITLE
Team17 Review: VnV - Traceability

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#52]
The traceability matrix looks good! Though you may want to write a test case for FR5 since there is no system test cases currently tracing back to that requirement. It would be helpful to test this requirement as well.

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! I have now added a test case for FR5 (FRT1-A3) and have updated the traceability matrix with this change. Now all functional requirements have at least one test case testing their functionality, and we may add more when we create our VnV report. 

You can view the changes here: 89e7138

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/2b905a3d-0524-4a45-967e-0f12bfaa2643)
