### ISSUE TITLE
Team 17 Review: Design - MIS 

### ISSUE THREAD

**Issue by AllisonRCook** [stanreee/sign-language-learning#68]
I noticed that the update of 'ExerciseTotalScore' mentioned in the Exercise module and the use of the Exercise Selection/History module. It would probably be best to mention the explicit transition/update in the Exercise Selection/History module.

This issue was created by Team 17 as part of the Design Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! The exercise selection/history module has now been removed as the team has decided it is out of scope for the application due to other constraints and the remining exercise module has been changed as a result of this. You can see the changes updated here: 37dc179
