### ISSUE TITLE
Mediapipe Timestamp Mismatch

### ISSUE THREAD

**Issue by Konadean** [stanreee/sign-language-learning#75]
```
ValueError: Graph has errors:
; Packet timestamp mismatch on a calculator receiving from stream "image". Current minimum expected timestamp is 7799923 but received 7799922. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
```

When running back-end for indeterminate lengths of time, this error occurs

**Comment by Konadean** [comment]
Timestamp issue is due to sheer volume of frame processing allowing recent frames to usurp and lack of concurrency enforcement with the way mediapipe processes each frame. Fixed with reducing frames sent from front-end to back-end and using threading mutexes to enforce concurrency

**Comment by ceyxasm** [comment]
Hey had the exact same issue.
Few questions and pointers
* Other similar issues talk about other streams like `model_select` and `in`. No one really got exact issue as `Packet timestamp mismatch on a calculator receiving from stream "image"`
* In my case as well, the number of calls to the model was indeed large. How did you solve it? To unblock, I am creating a new instance for each detection cycle.
