### ISSUE TITLE
Rev0 Demo - Usabiltiy Improvements: Practice Page Sign Confidence Feedback Display

### ISSUE THREAD

**Issue by Konadean** [stanreee/sign-language-learning#76]
Professor Smith recommended adding some form of percentage or word (Poor-OK-Good-Great-Amazing) to show how accurate the user's hand sign is on the practice page so the user does not learn the wrong sign.

**Comment by CassieBaldin** [comment]
The practice and exercise pages now have a "Confidence Level" underneath the result to show a user how close the model thinks their hand sign is to the correct one. This will help users to know to adjust their hand to better make the sign more accurate. 
![image](https://github.com/stanreee/sign-language-learning/assets/77757843/11833cb1-79a3-4a7d-a234-47bdad75cbba)
![image](https://github.com/stanreee/sign-language-learning/assets/77757843/d1f7a685-fb0c-49b8-952a-6fd51b5c8b34)

**Comment by CassieBaldin** [comment]
The commits pertaining to adding in the confidence level settings can be found here: 0dcd1e9 and c57eed9
