### ISSUE TITLE
Team 17 Review: VnV Report - Rewording of Objective

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#95]
The Objective starts with the mention about the VnV Plan but I believe it is just a little rewording. The VnV Report is about the evaluation of VnV Plan - How VnV Plan was implemented, what were the results of evaluation of the VnV Plan in action.

This issue was created by Team 17 as part of the VnV Report Review. Tagging marking TA as recommended @Lyuyang0130

[Review-Team17]

**Comment by edwardzhuang2001** [comment]
We disagree with this point but thank you for your feedback.
