### ISSUE TITLE
Team17 Review: VnV Report - Changes due to testing

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#96]
It would be helpful for the reader if the points in changes due to testing clearly mentioned what has been changed to what, not just what the status is after the change (eg. before we were planning that, but now we aim to do this instead). Like in the forst point, you should briefly mention what the previous plan was before the change.

This issue was created by Team 17 as part of the VnV Report Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by stanreee** [comment]
Thanks for the feedback! We addressed this issue in this commit here: 4f6d4e4
