### ISSUE TITLE
Team 17 Review: VnV Report - Missing Unit Tests

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#97]
There are two unit tests and the results of both the unit tests are "Fail". I am just looking for clarity if it means the application did not pass any unit tests at all? OR All the unit tests performed are not listed in the document? OR The team could not perform any more unit tests as of now and the teams to plan do it in near future?

This issue was created by Team 17 as part of the VnV Report Review. Tagging marking TA as recommended @Lyuyang0130

[Review-Team17]

**Comment by Konadean** [comment]
Unit Tests were performed at a later date, now available in VnVReport here: a3d5ec2477d0dcff3d79ba4fa5322f5e5c9b1c40
