### ISSUE TITLE
Team17 Review: VnV Report - Mode of tests

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#98]
It might be good to mention whether how the tests for FRs and NFRs were conducted, whether the passing condition was verified manually or a testing function was written for them, and why that method was deemed appropriate.

This issue was created by Team 17 as part of the VnV Report Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by Konadean** [comment]
Respectfully, we disagree. That information can be found within our VnVPlan.
