### ISSUE TITLE
Team 17 Review: VnV Report - VnV Plan is not updated

### ISSUE THREAD

**Issue by tusharagg1** [stanreee/sign-language-learning#99]
VnV Plan was not updated with respect to the VnV Report.
- VnV Report is missing unit tests that were outlined in the VnV Plan
- All automated testing was not performed/integrated/used as was mentioned about in the VnV Plan
- Etc.

This issue was created by Team 17 as part of the VnV Report Review. Tagging marking TA as recommended @Lyuyang0130

[Review-Team17]

**Comment by Konadean** [comment]
Fixed Here: 1f52c24c254fa4cb625be09f97ab3053b0861015
